-
  name: 'Redirect to Main Package'
  uriPattern: ''
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Standard'
    '@action':          'index'

-
  uriPattern: 'logs'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Standard'
    '@action':          'log'
