-
  name: 'Redirect to Main Package'
  uriPattern: ''
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Standard'
    '@action':          'index'

-
  name: 'Redirect to logs'
  uriPattern: 'logs'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Standard'
    '@action':          'log'

-
  name: 'Redirect to logs with pages'
  uriPattern: 'logs/page/{page}'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Standard'
    '@action':          'log'

-
  name: 'Api'
  uriPattern: 'api/{@action}'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Api'
    '@action':          'apply'

-
  name: 'Rulesets'
  uriPattern: 'rules'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Ruleset'
    '@action':          'index'

-
  name: 'Rulesets Actions with Id'
  uriPattern: 'rules/{@action}/{id}'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Ruleset'
    '@action':          'edit'

-
  name: 'Rulesets Actions'
  uriPattern: 'rules/{@action}'
  defaults:
    '@package':         'Guang.RuleEngine'
    '@controller':      'Ruleset'
    '@action':          'index'